#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["src/Server/HykeIt.Server.csproj", "src/Server/"]
COPY ["src/Shared/HykeIt.Shared.csproj", "src/Shared/"]
COPY ["src/Client/HykeIt.Client.csproj", "src/Client/"]
RUN dotnet restore "src/Server/HykeIt.Server.csproj"
COPY . .
WORKDIR "/src/src/Server"
RUN dotnet build "HykeIt.Server.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "HykeIt.Server.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "HykeIt.Server.dll"]